"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { getSessionUser } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { isSupabaseConfigured } from "@/lib/config/env";
import {
  getArtistTourPlannerReport,
  saveTourPlannerRun,
} from "@/lib/data/tour-planner";
import { buildTourPlannerReport, nextStopDateTime } from "@/lib/services/tour-planner.service";
import { syncAllStopEvents, tourWindowFromStops, uniqueTourSlug } from "@/lib/services/tours.service";
import type { TourPlannerReport } from "@/lib/types/tour-planner";
import { z } from "zod";

export type TourPlannerActionResult =
  | { ok: true; plan?: TourPlannerReport; tourId?: string }
  | { ok: false; error: string };

const applySchema = z.object({
  maxStops: z.coerce.number().int().min(1).max(12).optional(),
  title: z.string().min(2).max(120).optional(),
});

export async function generateTourPlanAction(): Promise<TourPlannerActionResult> {
  const user = await getSessionUser();
  if (!user) return { ok: false, error: "Sign in required" };
  if (!isSupabaseConfigured()) {
    const demo = await getArtistTourPlannerReport(user.id);
    if (!demo) return { ok: false, error: "Artist profile required" };
    return { ok: true, plan: demo.plan };
  }

  const supabase = await createClient();
  const { data: artist } = await supabase
    .from("artists")
    .select("id, slug, category")
    .eq("user_id", user.id)
    .maybeSingle();

  if (!artist) return { ok: false, error: "Complete artist profile first" };

  const plan = await buildTourPlannerReport(
    supabase,
    artist.id as string,
    (artist.category as string) ?? null
  );

  await saveTourPlannerRun(artist.id as string, plan);

  return { ok: true, plan };
}

export async function applyOptimizedTourPlanAction(input: unknown): Promise<TourPlannerActionResult> {
  const user = await getSessionUser();
  if (!user) return { ok: false, error: "Sign in required" };
  if (!isSupabaseConfigured()) {
    return { ok: false, error: "Connect Supabase to create tours" };
  }

  const parsed = applySchema.safeParse(input);
  if (!parsed.success) {
    return { ok: false, error: parsed.error.issues[0]?.message ?? "Invalid input" };
  }

  const supabase = await createClient();
  const { data: artist } = await supabase
    .from("artists")
    .select("id, slug, category")
    .eq("user_id", user.id)
    .maybeSingle();

  if (!artist) return { ok: false, error: "Artist profile required" };

  const plan = await buildTourPlannerReport(
    supabase,
    artist.id as string,
    (artist.category as string) ?? null
  );

  const maxStops = parsed.data.maxStops ?? 5;
  const stops = plan.recommendations.slice(0, maxStops);
  if (!stops.length) return { ok: false, error: "No cities to schedule — grow your fan heat map first." };

  const tourTitle =
    parsed.data.title?.trim() ||
    `AI Optimized Tour · ${new Date().toLocaleDateString(undefined, { month: "short", year: "numeric" })}`;

  const slug = uniqueTourSlug(tourTitle);
  const { data: tour, error: tourError } = await supabase
    .from("tours")
    .insert({
      artist_id: artist.id,
      title: tourTitle,
      slug,
      description: "Generated by LiveCircuit AI Tour Planner from fan heat, sales, and engagement signals.",
      status: "draft",
    })
    .select("id")
    .single();

  if (tourError || !tour) return { ok: false, error: tourError?.message ?? "Could not create tour" };

  const base = new Date();
  base.setDate(base.getDate() + 14);

  let order = 0;
  for (const rec of stops) {
    const scheduled = nextStopDateTime(base, order, rec.suggestedDayOfWeek, rec.suggestedHourLocal);
    const ticketPrice = Math.max(
      500,
      Math.round(rec.revenuePredictionCents / Math.max(rec.expectedAttendance, 1))
    );

    await supabase.from("tour_stops").insert({
      tour_id: tour.id,
      virtual_location_label: rec.cityLabel,
      venue_id: rec.venueId,
      venue_room_label: rec.venueSlug ? `${rec.cityLabel} room` : null,
      stop_order: order,
      scheduled_at: scheduled.toISOString(),
      timezone: "America/New_York",
      ticket_price_cents: ticketPrice,
      capacity: Math.max(rec.expectedAttendance, 100),
      merch_enabled: true,
    });
    order += 1;
  }

  const { data: allStops } = await supabase
    .from("tour_stops")
    .select("*")
    .eq("tour_id", tour.id)
    .order("stop_order", { ascending: true });

  const window = tourWindowFromStops(allStops ?? []);
  if (window.starts_at) {
    await supabase.from("tours").update(window).eq("id", tour.id);
  }

  const { data: tourRow } = await supabase.from("tours").select("*").eq("id", tour.id).single();
  if (tourRow && allStops?.length) {
    await syncAllStopEvents(supabase, tourRow, allStops);
  }

  await saveTourPlannerRun(artist.id as string, plan);

  revalidatePath("/artist/dashboard");
  revalidatePath("/artist/tour-planner");
  revalidatePath(`/artist/tours/${tour.id}`);

  return { ok: true, tourId: tour.id as string };
}

export async function applyOptimizedTourAndRedirectAction(input: unknown) {
  const result = await applyOptimizedTourPlanAction(input);
  if (!result.ok) return result;
  redirect(`/artist/tours/${result.tourId}`);
}
